### ISSUE TITLE
Discord crashes entirely when trying to translate messages sent by other people

### ISSUE THREAD

**Issue by mlsfaw** [cyyynthia/message-translate#5]

**Comment by Wolfhound905** [comment]
![image](https://user-images.githubusercontent.com/58155937/141519381-28ba69e2-87de-4ea4-9fb4-bfc03abe923b.png)

This happens when I translate another persons message

**Comment by governos** [comment]
Me too.

```
67f7a36165c38a0abe1f.js:130 TypeError: Cannot read property 'ConnectedSettingsModal' of undefined
    at C:\Programs\powercord\src\Powercord\plugins\message-translate\index.js:302:44
    at MessageLoggerV2.onDispatchEvent (C:\Programs\powercord\src\Powercord\plugins\bdCompat\plugins\MessageLoggerV2.plugin.js:2502:218)
    at Object.callback (C:\Programs\powercord\src\Powercord\plugins\bdCompat\plugins\MessageLoggerV2.plugin.js:665:37)
    at e.__powercordOriginal_dispatch (C:\Programs\powercord\src\Powercord\plugins\bdCompat\plugins\0PluginLibrary.plugin.js:1931:57)
    at e.dispatch (C:\Programs\powercord\src\fake_node_modules\powercord\injector\index.js:39:52)
    at open (C:\Programs\powercord\src\fake_node_modules\powercord\modal.js:15:11)
    at openSettings (C:\Programs\powercord\src\Powercord\plugins\message-translate\index.js:302:3)
    at module.exports (C:\Programs\powercord\src\Powercord\plugins\message-translate\TranslationHandler\translateAction.js:3:9)
    at action (C:\Programs\powercord\src\Powercord\plugins\message-translate\index.js:245:9)
```
